'use client'

import { useQueryClient } from '@tanstack/react-query'
import { useCallback, useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

import { api } from '@/lib/api'
import { fmtDate } from '@/lib/format'
import { generateQrSvg } from '@/lib/qr-matrix'
import type { MetaDTO } from '@/lib/types'

/**
 * Printable QR rack/shelf labels (Phase 2: "print QR stickers that map to the
 * zone/rack/shelf hierarchy"). One self-adhesive-style label per shelf
 * location: standard ISO QR vector SVG + hierarchy text, laid out as a cut-here
 * grid. Invisible on screen; pure black-on-white on paper (print.css).
 */

type MetaLocation = MetaDTO['locations'][number]

/** One cut-here label — QR matrix left, hierarchy text right. */
function RackLabel({ location }: { location: MetaLocation }) {
  const svg = generateQrSvg(location.fullPath, { margin: 1 })
  return (
    <div className="ps-label">
      <div
        className="ps-label-qr"
        aria-hidden="true"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <div className="ps-label-text">
        <div className="ps-label-zone">{location.zoneName}</div>
        <div className="ps-label-rack">
          Rack {location.rackCode} <span className="ps-label-sep">·</span> Shelf {location.code}
        </div>
        <div className="ps-label-path">{location.fullPath}</div>
        <div className="ps-label-caption">
          {location.warehouseName} · scan to open location
        </div>
      </div>
    </div>
  )
}

/** The printable sheet itself — header + cut-here label grid + footer. */
export function RackLabelPrint({
  locations,
  scopeLabel,
}: {
  locations: MetaLocation[]
  scopeLabel: string
}) {
  return (
    <div className="print-only print-sheet" aria-hidden="true">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '6mm' }}>
        <div>
          <div className="ps-title">Rack &amp; Shelf QR Labels</div>
          <div className="ps-subtitle">Print, cut along the dashed lines and affix one label per shelf front edge.</div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div className="ps-code">{scopeLabel}</div>
          <div className="ps-meta">
            {locations.length} {locations.length === 1 ? 'label' : 'labels'}
          </div>
        </div>
      </div>

      <div className="ps-label-grid">
        {locations.map((loc) => (
          <RackLabel key={loc.id} location={loc} />
        ))}
      </div>

      <div className="ps-small" style={{ marginTop: '4mm' }}>
        Generated by StockSense · {fmtDate(new Date())} · labels are deterministic — reprinting
        produces identical QR patterns per location.
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Print flow hook — resolves locations from the meta query, portals the sheet
// to document.body, waits for paint, opens the print dialog, cleans up.
// ---------------------------------------------------------------------------

export type RackLabelScope = { kind: 'ALL' } | { kind: 'RACK'; rackCode: string }

export function useRackLabelPrint() {
  const queryClient = useQueryClient()
  const [sheet, setSheet] = useState<{ locations: MetaLocation[]; scopeLabel: string } | null>(null)
  const mounted = useRef(true)

  useEffect(() => {
    mounted.current = true
    return () => {
      mounted.current = false
    }
  }, [])

  const print = useCallback(
    async (scope: RackLabelScope) => {
      let meta: MetaDTO
      try {
        meta = await queryClient.fetchQuery({
          queryKey: ['meta'],
          queryFn: () => api.get<MetaDTO>('/api/meta'),
        })
      } catch {
        return // meta is also fetched by the app normally; silent no-op here
      }
      const sorted = [...meta.locations].sort((a, b) =>
        a.fullPath.localeCompare(b.fullPath, undefined, { numeric: true })
      )
      const locations =
        scope.kind === 'ALL' ? sorted : sorted.filter((l) => l.rackCode === scope.rackCode)
      if (locations.length === 0 || !mounted.current) return
      const scopeLabel =
        scope.kind === 'ALL' ? 'ALL RACKS' : `RACK ${scope.rackCode}`
      setSheet({ locations, scopeLabel })

      // Give the browser two frames (or 300ms) to lay out + paint the sheet.
      await new Promise<void>((resolve) => {
        let done = false
        const finish = () => {
          if (!done) {
            done = true
            resolve()
          }
        }
        requestAnimationFrame(() => requestAnimationFrame(finish))
        setTimeout(finish, 300)
      })
      if (!mounted.current) return

      const cleanup = () => {
        window.removeEventListener('afterprint', cleanup)
        clearTimeout(fallback)
        if (mounted.current) setSheet(null)
      }
      const fallback = setTimeout(cleanup, 120_000)
      window.addEventListener('afterprint', cleanup)
      window.print()
    },
    [queryClient]
  )

  const portal = sheet
    ? createPortal(<RackLabelPrint locations={sheet.locations} scopeLabel={sheet.scopeLabel} />, document.body)
    : null

  return { print, portal, printing: sheet !== null }
}

/** Group meta locations by rack for the label-menu (sorted by zone/rack). */
export function groupLocationsByRack(locations: MetaLocation[]): { rackCode: string; zoneName: string; count: number }[] {
  const map = new Map<string, { rackCode: string; zoneName: string; count: number }>()
  for (const l of locations) {
    const existing = map.get(l.rackCode)
    if (existing) existing.count += 1
    else map.set(l.rackCode, { rackCode: l.rackCode, zoneName: l.zoneName, count: 1 })
  }
  return [...map.values()].sort(
    (a, b) => a.zoneName.localeCompare(b.zoneName) || a.rackCode.localeCompare(b.rackCode, undefined, { numeric: true })
  )
}
